### ISSUE TITLE
'mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)

### ISSUE THREAD

**Issue by unqjohnny** [bitcoincash-wallet/bitcoincashj#5]
i meet error below:
org.bitcoinj.core.RejectedTransactionException: Reject: tx  for reason 'mandatory-script-verify-flag-failed (Signature must use SIGHASH_FORKID)' (16)
        at org.bitcoinj.core.TransactionBroadcast$2.onPreMessageReceived(TransactionBroadcast.java:102) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at org.bitcoinj.core.Peer.processMessage(Peer.java:461) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:182) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-18.0.jar:?]
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [guava-18.0.jar:?]
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [bitcoincashj-core-0.14.5-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
2017-12-13 07:40:24 ERROR Peer [514]-[119.23.160.146]:8333 /Bitcoin ABC:0.16.1(EB8.0)/: Received Reject

**Comment by unqjohnny** [comment]
How can i solved it ? thanks very much

**Comment by HashEngineering** [comment]
SendRequest.setUseForkId() will be needed.

There is probably a better way to handle this.  to maintain backward
compatibility with bitcoinj unit tests, the default signature hash function
is the Bitcoin version.  But for Bitcoin Cash, it will be the replay
protection signature hash.

**Comment by unqjohnny** [comment]
thanks very much.. it works
